version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
    entrypoint: python manage.py runserver  0.0.0.0:8000
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - dev.env
    environment:
      - DJANGO_SETTINGS_MODULE=confetti.settings.dev
    depends_on:
      - db
  db:
    image: "postgres:13-alpine"
    env_file:
      - dev.env
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data

